name: CI

on:
  push:
    branches:
      - master
      - develop
    tags:
      - 'v*'

jobs:
  name: Build Prod
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
      images: |
        liampiginthecity/phoenix-auth-server
      tags: |
        type=ref,event=branch
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=sha
    - name: Build and Push Docker Images
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        target: phoenix_prod
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
